<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>comment</key>
		<string>PICO-8 (lua syntax 0.8)</string>
		<key>fileTypes</key>
		<array>
			<string>p8</string>
		</array>
		<key>foldingStartMarker</key>
		<string>^\s*\b(function|local\s+function|if|for)\b|{[ \t]*$|\[\[</string>
		<key>foldingStopMarker</key>
		<string>\bend\b|^\s*}|\]\]</string>
		<key>keyEquivalent</key>
		<string>^~L</string>
		<key>name</key>
		<string>PICO-8</string>
		<key>patterns</key>
		<array>
			<dict>
				<key>captures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>keyword.control.lua</string>
					</dict>
					<key>2</key>
					<dict>
						<key>name</key>
						<string>entity.name.function.scope.lua</string>
					</dict>
					<key>3</key>
					<dict>
						<key>name</key>
						<string>entity.name.function.lua</string>
					</dict>
					<key>4</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.parameters.begin.lua</string>
					</dict>
					<key>5</key>
					<dict>
						<key>name</key>
						<string>variable.parameter.function.lua</string>
					</dict>
					<key>6</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.parameters.end.lua</string>
					</dict>
				</dict>
				<key>match</key>
				<string>\b(function)\s+([a-zA-Z_.:]+[.:])?([a-zA-Z_]\w*)\s*(\()([^)]*)(\))</string>
				<key>name</key>
				<string>meta.function.lua</string>
			</dict>
			<dict>
				<key>match</key>
				<string>(?&lt;![\d.])\s0x[a-fA-F\d]+|\b\d+(\.\d+)?([eE]-?\d+)?|\.\d+([eE]-?\d+)?</string>
				<key>name</key>
				<string>constant.numeric.lua</string>
			</dict>
			<dict>
				<key>begin</key>
				<string>'</string>
				<key>beginCaptures</key>
				<dict>
					<key>0</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.string.begin.lua</string>
					</dict>
				</dict>
				<key>end</key>
				<string>'</string>
				<key>endCaptures</key>
				<dict>
					<key>0</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.string.end.lua</string>
					</dict>
				</dict>
				<key>name</key>
				<string>string.quoted.single.lua</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>\\.</string>
						<key>name</key>
						<string>constant.character.escape.lua</string>
					</dict>
				</array>
			</dict>
			<dict>
				<key>begin</key>
				<string>"</string>
				<key>beginCaptures</key>
				<dict>
					<key>0</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.string.begin.lua</string>
					</dict>
				</dict>
				<key>end</key>
				<string>"</string>
				<key>endCaptures</key>
				<dict>
					<key>0</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.string.end.lua</string>
					</dict>
				</dict>
				<key>name</key>
				<string>string.quoted.double.lua</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>\\.</string>
						<key>name</key>
						<string>constant.character.escape.lua</string>
					</dict>
				</array>
			</dict>
			<dict>
				<key>begin</key>
				<string>(?&lt;!--)\[(=*)\[</string>
				<key>beginCaptures</key>
				<dict>
					<key>0</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.string.begin.lua</string>
					</dict>
				</dict>
				<key>end</key>
				<string>\]\1\]</string>
				<key>endCaptures</key>
				<dict>
					<key>0</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.string.end.lua</string>
					</dict>
				</dict>
				<key>name</key>
				<string>string.quoted.other.multiline.lua</string>
			</dict>
			<dict>
				<key>begin</key>
				<string>--\[(=*)\[</string>
				<key>captures</key>
				<dict>
					<key>0</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.comment.lua</string>
					</dict>
				</dict>
				<key>end</key>
				<string>\]\1\]</string>
				<key>name</key>
				<string>comment.block.lua</string>
			</dict>
			<dict>
				<key>captures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.comment.lua</string>
					</dict>
				</dict>
				<key>match</key>
				<string>(--)(?!\[\[).*$\n?</string>
				<key>name</key>
				<string>comment.line.double-dash.lua</string>
			</dict>
			<dict>
				<key>match</key>
				<string>\b(break|do|else|for|if|elseif|return|then|repeat|while|until|end|function|local|in|goto)\b</string>
				<key>name</key>
				<string>keyword.control.lua</string>
			</dict>
			<dict>
				<key>match</key>
				<string>(?&lt;![^.]\.|:)\b(false|nil|true)\b</string>
				<key>name</key>
				<string>constant.language.lua</string>
			</dict>
			<dict>
				<key>match</key>
				<string>(?&lt;![^.]\.|:)\b(self)\b</string>
				<key>name</key>
				<string>variable.language.self.lua</string>
			</dict>
			<dict>
				<key>match</key>
				<string>(?&lt;![^.]\.|:)\b(_draw|_init|_update|_update60|abs|add|all|assert|atan2|band|bnot|bor|btn|btnp|bxor|camera|cartdata|cd|circ|circfill|clip|cls|cocreate|color|coresume|cos|costatus|count|cstore|cursor|del|dget|dir|dset|exit|export|fget|flip|flr|folder|foreach|fset|help|holdframe|import|info|install_demos|install_games|keyconfig|line|load|ls|map|mapdraw|max|memcpy|memset|menuitem|mget|mid|min|mkdir|mset|music|pairs|pal|palt|peek|pget|poke|print|printh|pset|reboot|rect|rectfill|reload|resume|rnd|run|save|setmetatable|sfx|sget|sgn|shl|shr|shutdown|sin|splore|spr|sqrt|srand|sset|sspr|stat|sub|time|type|yield)\b</string>
				<key>name</key>
				<string>support.function.lua</string>
			</dict>
			<dict>
				<key>match</key>
				<string>\b(and|or|not)\b</string>
				<key>name</key>
				<string>keyword.operator.lua</string>
			</dict>
			<dict>
				<key>match</key>
				<string>\(|\)|\;|\+=?|-=?|%=?|#|\*=?|\/=?|\^=?|\[|\]|==?|~=|&lt;=?|&gt;=?|,|\.\.?\.?|(?&lt;!\.)\.{2}(?!\.)</string>
				<key>name</key>
				<string>keyword.operator.punctuation.lua</string>
			</dict>
		</array>
		<key>scopeName</key>
		<string>source.p8</string>
		<key>uuid</key>
		<string>93E017CC-6F27-11D9-90EB-000D93589AF7</string>
	</dict>
</plist>
